
author:
    - name: Jae Skeete
      email: skeetej@vcu.edu

date: "APR 29 2025"

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
